import './globals.css'
import type { Metadata } from 'next'
import { Karla } from 'next/font/google'

import { Toaster } from 'sonner'
import { dark } from '@clerk/themes'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/theme-provider'

const font = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitch',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={font.className}>
          <ThemeProvider attribute='class' forcedTheme='dark' storageKey='twitch-theme'>
            <Toaster theme='light' position='bottom-center' />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
